services:

  postgres:
    image: postgres:16-alpine
    container_name: zabbix-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_2000
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zabbix-net

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:7.0-ubuntu-latest
    container_name: zabbix-server
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_2000
    ports:
      - "10051:10051"
    networks:
      - zabbix-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:7.0-ubuntu-latest
    container_name: zabbix-web
    restart: unless-stopped
    depends_on:
      - postgres
      - zabbix-server
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_2000
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Asia/Jakarta
    ports:
      - "8080:8080"
    networks:
      - zabbix-net

  zabbix-agent2:
    image: zabbix/zabbix-agent2:7.0-ubuntu-latest
    container_name: zabbix-agent2
    hostname: zabbix-agent2
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      ZBX_HOSTNAME: "zabbix-server"
      ZBX_SERVER_HOST: "zabbix-server,172.20.0.3"
      ZBX_SERVER_PORT: 10051
    privileged: true
    networks:
      - zabbix-net

networks:
  zabbix-net:
    driver: bridge

volumes:
  postgres_data: